name: create-pdf-from-markdown
on: [push, workflow_dispatch]
jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: install fonts for PDF
        run: |
          sudo apt install fonts-noto-cjk
      - name: install Node.js dependencies
        run: |
          yarn install
      - name: prepare script
        run: |
          chmod +x updateLastModifiedDate.sh
      - name: create pdf
        run: |
          yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
